/**
 * Generate `src/prompts/skills.gen.ts` from the vault's own skill files.
 *
 * The app has no Agent SDK and cannot discover `.claude/skills/` at runtime, so
 * the skill markdown and the root operating instructions are baked into the
 * bundle as string constants and shipped to the model as the system prompt.
 *
 * This keeps a single source of truth: the desktop Claude Code session and the
 * app read the exact same instructions, because the app's copy is generated
 * from them rather than hand-maintained. Editing a skill means re-running this
 * (it runs automatically before `npm test` and should be wired into the Expo
 * prebuild) and rebuilding the app.
 *
 * The generated file is git-ignored; it is a build artifact, not source.
 */

import { mkdirSync, readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname, "../..");
const SKILLS_DIR = join(REPO_ROOT, ".claude", "skills");
const OUT = resolve(import.meta.dirname, "../src/prompts/skills.gen.ts");

/** The skills the app actually drives. The rest stay desktop-only for now. */
const APP_SKILLS = ["capture", "daily-wrap", "daily-briefing"] as const;

function read(path: string): string {
  return readFileSync(path, "utf8");
}

/** A TypeScript string literal that survives any content, via JSON escaping. */
function literal(value: string): string {
  return JSON.stringify(value);
}

function main(): void {
  const operatingInstructions = read(join(REPO_ROOT, "CLAUDE.md"));

  const skills: Record<string, string> = {};
  for (const name of APP_SKILLS) {
    const skillPath = join(SKILLS_DIR, name, "SKILL.md");
    if (!statSync(skillPath).isFile()) {
      throw new Error(`Expected a skill at ${skillPath}. Is the vault intact?`);
    }
    skills[name] = read(skillPath);
  }

  // Sanity check: the whole point is fidelity to the vault, so fail loudly if a
  // skill directory the app expects has vanished upstream.
  const present = new Set(
    readdirSync(SKILLS_DIR, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name),
  );
  for (const name of APP_SKILLS) {
    if (!present.has(name)) throw new Error(`Skill "${name}" is missing from ${SKILLS_DIR}`);
  }

  const banner =
    "// GENERATED by scripts/gen-skills.ts from ../.claude/skills and ../CLAUDE.md.\n" +
    "// Do not edit by hand. Run `npm run gen:skills` after changing a skill.\n\n";

  const body = [
    `export const OPERATING_INSTRUCTIONS = ${literal(operatingInstructions)};`,
    "",
    "export const SKILLS = {",
    ...APP_SKILLS.map((name) => `  ${literal(name)}: ${literal(skills[name]!)},`),
    "} as const;",
    "",
    "export type SkillName = keyof typeof SKILLS;",
    "",
  ].join("\n");

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, banner + body);
  console.log(`Wrote ${OUT} (${APP_SKILLS.length} skills)`);
}

main();
